## Stappenplan en verdeling

1. aanmaken github
2. data preprocessing (verwijder duplicates and NaN)
3. bepaal de relevante features van de descriptors via een PCA
4. wat wordt test en wat wordt train
5. aanmaken model voor het maken van voorspellingen
    5.1 uitproberen welke methodes er toepasbaar zijn (random forest, k-NN)
    5.2 bepalen welke methode het beste is
6. verslag en presentatie 

1. Richard
2. Luuk, Richard
3. Robin, Tijn, Rik & Yael
4. 
5. Julien & Branco
6. 

## 5.1 Onderzoek over random forest methode
The random forest algorithm is an extension of the bagging method as it utilizes both bagging and feature randomness to create an uncorrelated forest of decision trees. While decision trees consider all the possible feature splits, random forests only select a subset of those features.

Random forest algorithms have three main hyperparameters, which need to be set before training. These include node size, the number of trees, and the number of features sampled. From there, the random forest classifier can be used to solve for regression or classification problems.

> Dit betekent dat alle descriptors onze features zijn waarvan per tree een random keuze wordt gemaakt. 
> The nodesize parameter specifies the minimum number of observations in a terminal node. Setting it lower leads to trees with a larger depth which means that more splits are performed until the terminal nodes.

The random forest algorithm is made up of a collection of decision trees, and each tree in the ensemble is comprised of a data sample drawn from a training set with replacement, called the bootstrap sample. Of that training sample, one-third of it is set aside as test data, known as the out-of-bag (oob) sample, which we’ll come back to later. Another instance of randomness is then injected through feature bagging, adding more diversity to the dataset and reducing the correlation among decision trees. Depending on the type of problem, the determination of the prediction will vary.

> Dit geeft dus aan dat onze verschillende moleculen niet allemaal tegelijk moeten worden gebruikt maar in secties. De grote van deze sectie is denk ik voor onszelf te bepalen. 

In [5]:
#Useful functions:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
#Hiermee importeren we de RandomForestClassifier functie.

# Load the dataset
data = load_iris()
X = data.data
y = data.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf = RandomForestClassifier()
#RandomForestClassifier() kan veel parameters gebruiken. De belangrijkste hiervan is n_estimators. Deze parameter bepaalt de hoeveelheid decision trees. Sommige parameters, zoals max_leaf_nodes, welke de maximale hoeveelheid verschillende ‘kruispunten’ in elke decision tree bepaalt, kunnen worden gebruikt om het model te optimaliseren.

rf.fit(X_train, y_train)
#Deze functie fit het model op onze data. Xtrain en Ytrain zijn in dit geval training data. Dat is dus die file tested_molecules.csv. 

Ypredicted = rf.predict(X_test)
#Nadat het model is gefit, kunnen met deze functie de waardes voor onze test data berekend worden.

ChatGPT test

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.datasets import load_iris

# Load the dataset
data = load_iris()
X = data.data
y = data.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Random Forest Classifier
rf = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
rf.fit(X_train, y_train)

# Make predictions
y_pred = rf.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print("Confusion Matrix:")
print(cm)
print("Classification Report:")
print(report)

Accuracy: 1.0
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



## try random forest with our data

In [5]:
data=pd.read_csv('cleaned_descriptor_data',index_col=0)
data.head()

BertzCT  ExactMolWt     Kappa1  \
SMILES                                                                   
C=C(C)c1nc(N)nc(N)n1                 272.774159  151.085795   7.456952   
C=C(Cl)COc1ccc2c(C)cc(=O)oc2c1       628.087447  250.039672  11.736876   
C=CCNC(=O)CCCC(=O)NCC=C              212.742421  210.136828  13.420000   
C=CCOn1c(=O)c(C)[n+]([O-])c2ccccc21  631.418725  232.084792  11.193326   
C=CCn1cc(Cl)c(=O)n(CC=C)c1=O         499.124344  226.050905  11.524349   

                                     NOCount  BCUT2D_LOGPLOW  \
SMILES                                                         
C=C(C)c1nc(N)nc(N)n1                       5       -2.047656   
C=C(Cl)COc1ccc2c(C)cc(=O)oc2c1             3       -1.991714   
C=CCNC(=O)CCCC(=O)NCC=C                    4       -2.250322   
C=CCOn1c(=O)c(C)[n+]([O-])c2ccccc21        5       -2.432024   
C=CCn1cc(Cl)c(=O)n(CC=C)c1=O               4       -2.388420   

                                     NumValenceElectrons  HeavyAtomCount  \
SMILES                                                                     
C=C(C)c1nc(N)nc(N)n1                                  58              11   
C=C(Cl)COc1ccc2c(C)cc(=O)oc2c1                        88              17   
C=CCNC(=O)CCCC(=O)NCC=C                               84              15   
C=CCOn1c(=O)c(C)[n+]([O-])c2ccccc21                   88              17   
C=CCn1cc(Cl)c(=O)n(CC=C)c1=O                          80              15   

                                        Chi2n  PEOE_VSA1    Kappa2  ...  \
SMILES                                                              ...   
C=C(C)c1nc(N)nc(N)n1                 2.155745  11.467335  2.531038  ...   
C=C(Cl)COc1ccc2c(C)cc(=O)oc2c1       3.712350   9.154014  4.634332  ...   
C=CCNC(=O)CCCC(=O)NCC=C              3.039058  10.633577  8.993915  ...   
C=CCOn1c(=O)c(C)[n+]([O-])c2ccccc21  3.552474  10.044842  4.288212  ...   
C=CCn1cc(Cl)c(=O)n(CC=C)c1=O         2.905081   0.000000  4.794989  ...   

                                     HallKierAlpha  NumHeteroatoms  \
SMILES                                                               
C=C(C)c1nc(N)nc(N)n1                         -1.65               5   
C=C(Cl)COc1ccc2c(C)cc(=O)oc2c1               -1.74               4   
C=CCNC(=O)CCCC(=O)NCC=C                      -1.58               4   
C=CCOn1c(=O)c(C)[n+]([O-])c2ccccc21          -2.30               5   
C=CCn1cc(Cl)c(=O)n(CC=C)c1=O                 -1.55               5   

                                     SlogP_VSA11   TPSA     Chi4v  \
SMILES                                                              
C=C(C)c1nc(N)nc(N)n1                    0.000000  90.71  0.600230   
C=C(Cl)COc1ccc2c(C)cc(=O)oc2c1          5.749512  39.44  1.611225   
C=CCNC(=O)CCCC(=O)NCC=C                 0.000000  58.20  0.958288   
C=CCOn1c(=O)c(C)[n+]([O-])c2ccccc21     0.000000  58.17  1.586949   
C=CCn1cc(Cl)c(=O)n(CC=C)c1=O            0.000000  44.00  1.397909   

                                     NumRotatableBonds  fr_ether     Chi1v  \
SMILES                                                                       
C=C(C)c1nc(N)nc(N)n1                                 1         0  3.022544   
C=C(Cl)COc1ccc2c(C)cc(=O)oc2c1                       3         1  5.444609   
C=CCNC(=O)CCCC(=O)NCC=C                              8         0  4.955455   
C=CCOn1c(=O)c(C)[n+]([O-])c2ccccc21                  3         0  5.146222   
C=CCn1cc(Cl)c(=O)n(CC=C)c1=O                         4         0  4.708338   

                                     ERK2_inhibition  PKM2_inhibition  
SMILES                                                                 
C=C(C)c1nc(N)nc(N)n1                               0                0  
C=C(Cl)COc1ccc2c(C)cc(=O)oc2c1                     0                0  
C=CCNC(=O)CCCC(=O)NCC=C                            0                0  
C=CCOn1c(=O)c(C)[n+]([O-])c2ccccc21                0                0  
C=CCn1cc(Cl)c(=O)n(CC=C)c1=O                       0       

In [6]:

X = data.drop(columns='ERK2_inhibition').drop(columns='PKM2_inhibition').copy()
y = data['ERK2_inhibition']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Initialize the Random Forest Classifier
rf = RandomForestClassifier(n_estimators=1100)

# Train the model
rf.fit(X_train, y_train)

# Make predictions
y_pred = rf.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print("Confusion Matrix:")
print(cm)
print("Classification Report:")
print(report)
print(y_pred)

Accuracy: 0.9419642857142857
Confusion Matrix:
[[211   0]
 [ 13   0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.94      1.00      0.97       211
           1       0.00      0.00      0.00        13

    accuracy                           0.94       224
   macro avg       0.47      0.50      0.49       224
weighted avg       0.89      0.94      0.91       224

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0]


c:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


For now, the random forest just predicts every molecule to have no inhibition and this gives a pretty high accuracy. We will probably need a workaround this